Repository dog-house-development/poodl, pull requests merged in 2019-03, with the labels that each got.

#279 Build member profiles
  client/src/actions/memberActions.js
  client/src/actions/types.js
  client/src/assets/stylesheets/ui/panel.scss
  client/src/components/pages/views/MemberProfile.js
  client/src/components/pages/views/tests/__snapshots__/MemberProfile.test.js.snap
  client/src/components/ui/EditableBoolean.js
  client/src/components/ui/EditableField.js
  client/src/reducers/membersReducer.js
  models/Member.js
  routes/api/members.js
  test/member_test.js
Labels: biscuit

#286 Fix edit member functionality
  client/src/actions/memberActions.js
  client/src/actions/types.js
  client/src/assets/stylesheets/pages/viewAll.scss
  client/src/components/App.js
  client/src/components/pages/member/MemberProfile.js
  client/src/components/pages/member/ViewAllMembers.js
  client/src/components/pages/member/memberFields.js
  client/src/components/pages/member/tests/MemberProfile.test.js
  client/src/components/pages/member/tests/ViewAllMembers.test.js
  client/src/components/pages/member/tests/__snapshots__/MemberProfile.test.js.snap
  client/src/components/pages/member/tests/__snapshots__/ViewAllMembers.test.js.snap
  client/src/components/pages/views/MemberProfile.js
  client/src/components/pages/views/tests/__snapshots__/MemberProfile.test.js.snap
  client/src/components/ui/Button.js
  client/src/components/ui/EditableBoolean.js
  client/src/components/ui/EditableCheckBox.js
  client/src/components/ui/EditableField.js
  client/src/components/ui/EditableRadio.js
  client/src/reducers/membersReducer.js
  models/Member.js
  routes/api/members.js
Labels: raisin

#292 Refactor state and actions
  client/src/actions/activityActions.js
  client/src/actions/adminActions.js
  client/src/actions/authActions.js
  client/src/actions/memberActions.js
  client/src/actions/tests/adminActions.test.js
  client/src/actions/tests/authActions.test.js
  client/src/actions/tests/memberActions.test.js
  client/src/actions/tests/volunteerActions.test.js
  client/src/actions/types.js
  client/src/actions/utils/ActionHelper.js
  client/src/actions/volunteerActions.js
  client/src/components/App.js
  client/src/components/layout/Navbar.js
  client/src/components/layout/tests/Navbar.test.js
  client/src/components/pages/activities/AddActivity.js
  client/src/components/pages/activities/ViewAllActivities.js
  client/src/components/pages/activities/tests/AddActivity.test.js
  client/src/components/pages/activities/tests/ViewAllActivities.test.js
  client/src/components/pages/activities/tests/__snapshots__/ViewAllActivities.test.js.snap
  client/src/components/pages/admins/AdminProfile.js
  client/src/components/pages/admins/Register.js
  client/src/components/pages/admins/ViewAllAdmins.js
  client/src/components/pages/admins/ViewAllVolunteers.js
  client/src/components/pages/admins/VolunteerProfile.js
  client/src/components/pages/admins/tests/AdminProfile.test.js
  client/src/components/pages/admins/tests/Register.test.js
  client/src/components/pages/admins/tests/ViewAllAdmins.test.js
  client/src/components/pages/admins/tests/ViewAllVolunteers.test.js
  client/src/components/pages/admins/tests/VolunteerProfile.test.js
  client/src/components/pages/admins/tests/__snapshots__/AdminProfile.test.js.snap
  client/src/components/pages/admins/tests/__snapshots__/Register.test.js.snap
  client/src/components/pages/admins/tests/__snapshots__/VolunteerProfile.test.js.snap
  client/src/components/pages/auth/Login.js
  client/src/components/pages/auth/tests/Login.test.js
  client/src/components/pages/auth/tests/__snapshots__/Login.test.js.snap
  client/src/components/pages/dashboard/Dashboard.js
  client/src/components/pages/dashboard/tests/Dashboard.test.js
  client/src/components/pages/login/Login.js
  client/src/components/pages/login/tests/Login.test.js
  client/src/components/pages/members/MemberProfile.js
  client/src/components/pages/members/ViewAllMembers.js
  client/src/components/pages/members/tests/MemberProfile.test.js
  client/src/components/pages/members/tests/ViewAllMembers.test.js
  client/src/components/pages/members/tests/__snapshots__/MemberProfile.test.js.snap
  client/src/reducers/activitiesReducer.js
  client/src/reducers/adminsReducer.js
  client/src/reducers/authReducer.js
  client/src/reducers/errorReducer.js
  client/src/reducers/index.js
  client/src/reducers/membersReducer.js
  client/src/reducers/volunteersReducer.js
Labels: groom

#297 Refactor API tests
  package.json
  routes/api/utils/apiHelper.js
  server.js
  test/activites_tests.js
  test/admin_tests.js
  test/api/index.test.js
  test/api/suites/activities/activities.json
  test/api/suites/activities/activities.test.js
  test/api/suites/admins/admins.json
  test/api/suites/admins/admins.test.js
  test/api/suites/members/members.json
  test/api/suites/members/members.test.js
  test/api/suites/seniorCenters/seniorCenters.json
  test/api/suites/seniorCenters/seniorCenters.test.js
  test/api/suites/services/services.json
  test/api/suites/services/services.test.js
  test/api/utils/expectNoErrors.js
  test/member_test.js
  test/mocha.opts
  test/seniorCenter_tests.js
  test/services_tests.js
Labels: biscuit

#307 Fix combobox
  client/src/components/ui/Field.js
  client/src/components/ui/tests/__snapshots__/Field.test.js.snap
  client/src/components/ui/tests/__snapshots__/Form.test.js.snap
Labels: raisin

#313 HOTFIX Remove package-lock.json
  package-lock.json
Labels: raisin

#310 Implement edit admin
  client/src/components/pages/admins/AdminProfile.js
  client/src/components/pages/admins/adminFields.js
  client/src/components/pages/admins/tests/AdminProfile.test.js
  client/src/components/pages/admins/tests/__snapshots__/AdminProfile.test.js.snap
Labels: biscuit

#311 Implement edit volunteer
  client/src/components/pages/admins/AdminProfile.js
  client/src/components/pages/admins/adminFields.js
  client/src/components/pages/admins/tests/AdminProfile.test.js
  client/src/components/pages/admins/tests/__snapshots__/AdminProfile.test.js.snap
  client/src/components/pages/volunteers/VolunteerProfile.js
  client/src/components/pages/volunteers/tests/VolunteerProfile.test.js
  client/src/components/pages/volunteers/tests/__snapshots__/VolunteerProfile.test.js.snap
  client/src/components/pages/volunteers/volunteerFields.js
  client/src/components/ui/EditableMultiCheckbox.js
  client/src/components/ui/EditableProfile.js
  models/Admin.js
  test/api/suites/admins/admins.json
Labels: biscuit

#315 Hide/show button in member check-in for ended activities
  client/src/components/pages/members/memberCheckIn/pages/SelectActivities.js
Labels: biscuit

#320 Fix member is new or renewal
  client/src/components/pages/members/memberFields.js
  client/src/components/pages/members/tests/__snapshots__/MemberProfile.test.js.snap
Labels: raisin
