Repository dog-house-development/poodl, pull requests merged in 2019-04, with the labels that each got.

#347 Better search for member check in
  client/src/components/pages/members/memberCheckIn/pages/FindMember.js
  client/src/components/ui/SearchField.js
Labels: biscuit

#348 Add controls to filter DataGrid results
  client/src/assets/stylesheets/_presets.scss
  client/src/assets/stylesheets/ui/field.scss
  client/src/components/pages/admins/tests/__snapshots__/ViewAllAdmins.test.js.snap
  client/src/components/pages/members/tests/__snapshots__/ViewAllMembers.test.js.snap
  client/src/components/pages/volunteers/tests/__snapshots__/ViewAllVolunteers.test.js.snap
  client/src/components/ui/DataGrid.js
  client/src/components/ui/Field.js
  client/src/components/ui/tests/__snapshots__/DataGrid.test.js.snap
  client/src/components/ui/tests/__snapshots__/Field.test.js.snap
  client/src/components/ui/tests/__snapshots__/Form.test.js.snap
Labels: biscuit

#350 Add button in view all for member checkin
  client/src/assets/stylesheets/_presets.scss
  client/src/assets/stylesheets/pages/viewAll.scss
  client/src/assets/stylesheets/ui/datagrid.scss
  client/src/assets/stylesheets/ui/panel.scss
  client/src/assets/stylesheets/ui/viewByDate.scss
  client/src/components/pages/members/ViewAllMembers.js
  client/src/components/pages/members/tests/__snapshots__/ViewAllMembers.test.js.snap
Labels: biscuit

#353 Direct user to correct url when logged in
  client/src/components/pages/login/Login.js
  client/src/components/pages/login/tests/Login.test.js
  client/src/components/private-route/PrivateRoute.js
Labels: biscuit

#352 Logout admin when they navigate away from member check-in by clicking home link in footer
  client/src/assets/stylesheets/layout/header.scss
  client/src/assets/stylesheets/ui/dropdown.scss
  client/src/components/layout/Navbar.js
  client/src/components/layout/tests/Navbar.test.js
  client/src/components/pages/members/memberCheckIn/MemberCheckIn.js
  client/src/components/pages/members/memberCheckIn/pages/SelectActivities.js
  client/src/components/tests/__snapshots__/App.test.js.snap
  client/src/reducers/authReducer.js
  client/src/utils/Utils.js
  client/src/utils/formatDateRange.js
Labels: biscuit

#354 Make util for searching objects and fix find member
  client/src/assets/stylesheets/layout/header.scss
  client/src/components/pages/members/memberCheckIn/pages/FindMember.js
  client/src/components/ui/DataGrid.js
  client/src/components/ui/SearchField.js
  client/src/utils/Utils.js
Labels: biscuit, raisin

#361 Escape regex
  client/src/components/ui/ComboBox.js
  client/src/utils/Utils.js
Labels: raisin

#375 Everything for services
  client/src/actions/serviceActions.js
  client/src/actions/types.js
  client/src/actions/utils/ActionHelper.js
  client/src/assets/stylesheets/App.scss
  client/src/assets/stylesheets/layout/header.scss
  client/src/assets/stylesheets/pages/manageServices.scss
  client/src/assets/stylesheets/pages/viewAll.scss
  client/src/assets/stylesheets/pages/viewService.scss
  client/src/assets/stylesheets/ui/buttons.scss
  client/src/assets/stylesheets/ui/combobox.scss
  client/src/assets/stylesheets/ui/datagrid.scss
  client/src/assets/stylesheets/ui/dynamicForm.scss
  client/src/assets/stylesheets/ui/field.scss
  client/src/assets/stylesheets/ui/list.scss
  client/src/assets/stylesheets/ui/panel.scss
  client/src/assets/stylesheets/ui/tabs.scss
  client/src/components/App.js
  client/src/components/pages/members/MemberProfile.js
  client/src/components/pages/members/tests/MemberProfile.test.js
  client/src/components/pages/members/tests/__snapshots__/MemberProfile.test.js.snap
  client/src/components/pages/services/AddService.js
  client/src/components/pages/services/ManageServices.js
  client/src/components/pages/services/ServiceList.js
  client/src/components/pages/services/ViewService.js
  client/src/components/pages/services/serviceInputs.js
  client/src/components/tests/__snapshots__/App.test.js.snap
  client/src/components/ui/Button.js
  client/src/components/ui/ComboBox.js
  client/src/components/ui/DynamicForm.js
  client/src/components/ui/List.js
  client/src/components/ui/TabPage.js
  client/src/components/ui/tests/__snapshots__/Button.test.js.snap
  client/src/reducers/index.js
  client/src/reducers/servicesReducer.js
  models/Service.js
  test/api/suites/services/services.json
Labels: biscuit

#378 Fix form error calculation
  client/src/components/pages/members/RegisterMember.js
  client/src/components/pages/members/tests/__snapshots__/MemberProfile.test.js.snap
  client/src/components/pages/volunteers/RegisterVolunteer.js
  client/src/components/pages/volunteers/tests/__snapshots__/VolunteerProfile.test.js.snap
  client/src/components/ui/DynamicForm.js
Labels: raisin

#381 Change way service and member is being fetched
  client/src/components/pages/services/ViewService.js
Labels: groom

#382 Extract view by date from dashboard and add icons to tabs
  client/src/assets/stylesheets/ui/tabs.scss
  client/src/assets/stylesheets/ui/viewByDate.scss
  client/src/components/pages/activities/ViewActivitiesByDate.js
  client/src/components/pages/activities/ViewActivity.js
  client/src/components/pages/dashboard/Dashboard.js
  client/src/components/pages/dashboard/tests/Dashboard.test.js
  client/src/components/pages/members/MemberProfile.js
  client/src/components/pages/members/tests/__snapshots__/MemberProfile.test.js.snap
  client/src/components/ui/TabPage.js
  client/src/components/ui/ViewByDate.js
Labels: biscuit, groom

#383 Add numbers to tabs
  client/src/assets/stylesheets/ui/tabs.scss
  client/src/components/pages/activities/ViewActivity.js
  client/src/components/pages/members/MemberProfile.js
  client/src/components/pages/members/tests/MemberProfile.test.js
  client/src/components/pages/members/tests/__snapshots__/MemberProfile.test.js.snap
  client/src/components/pages/services/ManageServices.js
  client/src/components/pages/services/ServiceList.js
  client/src/components/ui/TabPage.js
Labels: biscuit

#386 Fix deleting service bug
  client/src/components/pages/services/ViewService.js
Labels: raisin

#391 Fix tab click on numbers
  client/src/assets/stylesheets/ui/tabs.scss
Labels: raisin

#387 Member self sign up
  client/src/actions/memberActions.js
  client/src/assets/stylesheets/pages/memberCheckIn.scss
  client/src/components/pages/members/memberCheckIn/MemberCheckIn.js
  client/src/components/pages/members/memberCheckIn/pages/FindMember.js
  client/src/components/pages/members/memberCheckIn/pages/SelfRegisterMember.js
Labels: biscuit

#394 Fix search results leaving page on find member
  client/src/assets/stylesheets/ui/searchField.scss
Labels: raisin

#398 Register and edit admin with dynamic form
  client/src/components/pages/admins/AdminProfile.js
  client/src/components/pages/admins/RegisterAdmin.js
  client/src/components/pages/admins/adminFields.js
  client/src/components/pages/admins/adminInputs.js
  client/src/components/pages/admins/tests/RegisterAdmin.test.js
  client/src/components/pages/admins/tests/__snapshots__/AdminProfile.test.js.snap
  client/src/components/pages/admins/tests/__snapshots__/RegisterAdmin.test.js.snap
  client/src/components/ui/EditableCheckBox.js
  client/src/components/ui/EditableField.js
  client/src/components/ui/EditableMultiCheckbox.js
  client/src/components/ui/EditableProfile.js
  client/src/components/ui/EditableRadio.js
Labels: groom

#401 Save last tab in url
  client/src/components/pages/members/tests/__snapshots__/MemberProfile.test.js.snap
  client/src/components/ui/TabPage.js
  client/src/utils/Utils.js
Labels: biscuit

#405 Stop deleting yourself
  client/src/components/pages/admins/AdminProfile.js
  client/src/components/pages/admins/tests/AdminProfile.test.js
  client/src/components/pages/admins/tests/__snapshots__/AdminProfile.test.js.snap
Labels: raisin

#406 Add clear button and icon options to field
  client/src/assets/stylesheets/ui/field.scss
  client/src/assets/stylesheets/ui/tabs.scss
  client/src/components/pages/members/memberCheckIn/pages/FindMember.js
  client/src/components/ui/DataGrid.js
  client/src/components/ui/Field.js
  client/src/components/ui/SearchField.js
  client/src/components/ui/tests/__snapshots__/DataGrid.test.js.snap
Labels: biscuit

#408 Route with tabs
  client/src/components/ui/TabPage.js
  client/src/utils/Utils.js
Labels: biscuit

#420 Styling changes to everything
  client/src/assets/stylesheets/_presets.scss
  client/src/assets/stylesheets/layout/header.scss
  client/src/assets/stylesheets/pages/manageServices.scss
  client/src/assets/stylesheets/ui/buttons.scss
  client/src/assets/stylesheets/ui/dropdown.scss
  client/src/assets/stylesheets/ui/field.scss
  client/src/assets/stylesheets/ui/loading.scss
  client/src/assets/stylesheets/ui/viewByDate.scss
  client/src/components/layout/Navbar.js
  client/src/components/layout/tests/__snapshots__/Navbar.test.js.snap
  client/src/components/pages/activities/AddActivity.js
  client/src/components/pages/activities/ViewActivity.js
  client/src/components/pages/activities/ViewAllActivities.js
  client/src/components/pages/admins/AdminProfile.js
  client/src/components/pages/admins/RegisterAdmin.js
  client/src/components/pages/admins/ViewAllAdmins.js
  client/src/components/pages/admins/tests/__snapshots__/AdminProfile.test.js.snap
  client/src/components/pages/admins/tests/__snapshots__/RegisterAdmin.test.js.snap
  client/src/components/pages/admins/tests/__snapshots__/ViewAllAdmins.test.js.snap
  client/src/components/pages/dashboard/Dashboard.js
  client/src/components/pages/login/Login.js
  client/src/components/pages/login/tests/__snapshots__/Login.test.js.snap
  client/src/components/pages/members/MemberProfile.js
  client/src/components/pages/members/RegisterMember.js
  client/src/components/pages/members/ViewAllMembers.js
  client/src/components/pages/members/memberCheckIn/pages/SelfRegisterMember.js
  client/src/components/pages/members/tests/__snapshots__/MemberProfile.test.js.snap
  client/src/components/pages/members/tests/__snapshots__/RegisterMember.test.js.snap
  client/src/components/pages/members/tests/__snapshots__/ViewAllMembers.test.js.snap
  client/src/components/pages/reports/Reports.js
  client/src/components/pages/services/ViewService.js
  client/src/components/pages/volunteers/RegisterVolunteer.js
  client/src/components/pages/volunteers/ViewAllVolunteers.js
  client/src/components/pages/volunteers/VolunteerProfile.js
  client/src/components/pages/volunteers/tests/__snapshots__/RegisterVolunteer.test.js.snap
  client/src/components/pages/volunteers/tests/__snapshots__/ViewAllVolunteers.test.js.snap
  client/src/components/pages/volunteers/tests/__snapshots__/VolunteerProfile.test.js.snap
  client/src/components/ui/Button.js
  client/src/components/ui/DeleteButton.js
  client/src/components/ui/tests/__snapshots__/Button.test.js.snap
Labels: groom

#426 Member check in unit tests
  client/src/components/layout/Navbar.js
  client/src/components/layout/tests/Navbar.test.js
  client/src/components/layout/tests/__snapshots__/Navbar.test.js.snap
  client/src/components/pages/members/memberCheckIn/MemberCheckIn.js
  client/src/components/pages/members/memberCheckIn/pages/Finished.js
  client/src/components/pages/members/memberCheckIn/pages/SelectActivities.js
  client/src/components/pages/members/memberCheckIn/pages/tests/FindMember.test.js
  client/src/components/pages/members/memberCheckIn/pages/tests/Finished.test.js
  client/src/components/pages/members/memberCheckIn/pages/tests/SelectActivities.test.js
  client/src/components/pages/members/memberCheckIn/pages/tests/SelfRegisterMember.test.js
  client/src/components/pages/members/memberCheckIn/pages/tests/__snapshots__/FindMember.test.js.snap
  client/src/components/pages/members/memberCheckIn/pages/tests/__snapshots__/Finished.test.js.snap
  client/src/components/pages/members/memberCheckIn/pages/tests/__snapshots__/SelectActivities.test.js.snap
  client/src/components/pages/members/memberCheckIn/pages/tests/__snapshots__/SelfRegisterMember.test.js.snap
  client/src/components/pages/members/memberCheckIn/tests/MemberCheckIn.test.js
  client/src/components/pages/members/memberCheckIn/tests/__snapshots__/MemberCheckIn.test.js.snap
  client/src/components/pages/volunteers/ViewAllVolunteers.js
  client/src/components/pages/volunteers/tests/__snapshots__/ViewAllVolunteers.test.js.snap
Labels: tests

#433 Add some coverage to reducer and other files
  client/src/components/layout/tests/Navbar.test.js
  client/src/components/pages/admins/tests/RegisterAdmin.test.js
  client/src/components/pages/admins/tests/__snapshots__/RegisterAdmin.test.js.snap
  client/src/components/pages/login/tests/Login.test.js
  client/src/components/ui/tests/Button.test.js
  client/src/components/ui/tests/CheckBox.test.js
  client/src/components/ui/tests/DataGrid.test.js
  client/src/components/ui/tests/DeleteButton.test.js
  client/src/components/ui/tests/Dropdown.test.js
  client/src/components/ui/tests/__snapshots__/Button.test.js.snap
  client/src/components/ui/tests/__snapshots__/CheckBox.test.js.snap
  client/src/components/ui/tests/__snapshots__/DataGrid.test.js.snap
  client/src/components/ui/tests/__snapshots__/DeleteButton.test.js.snap
  client/src/reducers/servicesReducer.js
  client/src/reducers/tests/activitiesReducer.test.js
  client/src/reducers/tests/adminsReducer.test.js
  client/src/reducers/tests/authReducer.test.js
  client/src/reducers/tests/data/activities.json
  client/src/reducers/tests/data/admins.json
  client/src/reducers/tests/data/members.json
  client/src/reducers/tests/data/services.json
  client/src/reducers/tests/membersReducer.test.js
  client/src/reducers/tests/servicesReducer.test.js
  client/src/reducers/tests/volunteersReducer.test.js
  client/src/reducers/volunteersReducer.js
Labels: tests
